// Code generated by protoc-gen-go.
// source: protobuf-rpc-duplex.proto
// DO NOT EDIT!

/*
Package protobufclient is a generated protocol buffer package.

It is generated from these files:
	protobuf-rpc-duplex.proto

It has these top-level messages:
	ConnectRequest
	ConnectResponse
	RpcRequest
	RpcResponse
	RpcError
	RpcCancel
	OobResponse
	OobMessage
	WirePayload
*/
package protobufclient

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ConnectErrorCode int32

const (
	ConnectErrorCode_ALREADY_CONNECTED ConnectErrorCode = 0
)

var ConnectErrorCode_name = map[int32]string{
	0: "ALREADY_CONNECTED",
}
var ConnectErrorCode_value = map[string]int32{
	"ALREADY_CONNECTED": 0,
}

func (x ConnectErrorCode) Enum() *ConnectErrorCode {
	p := new(ConnectErrorCode)
	*p = x
	return p
}
func (x ConnectErrorCode) String() string {
	return proto.EnumName(ConnectErrorCode_name, int32(x))
}
func (x *ConnectErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConnectErrorCode_value, data, "ConnectErrorCode")
	if err != nil {
		return err
	}
	*x = ConnectErrorCode(value)
	return nil
}

type ConnectRequest struct {
	CorrelationId    *int32  `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	ClientHostName   *string `protobuf:"bytes,2,req,name=clientHostName" json:"clientHostName,omitempty"`
	ClientPort       *int32  `protobuf:"varint,3,req,name=clientPort" json:"clientPort,omitempty"`
	ClientPID        *string `protobuf:"bytes,4,req,name=clientPID" json:"clientPID,omitempty"`
	Compress         *bool   `protobuf:"varint,5,opt,name=compress" json:"compress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}

func (m *ConnectRequest) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *ConnectRequest) GetClientHostName() string {
	if m != nil && m.ClientHostName != nil {
		return *m.ClientHostName
	}
	return ""
}

func (m *ConnectRequest) GetClientPort() int32 {
	if m != nil && m.ClientPort != nil {
		return *m.ClientPort
	}
	return 0
}

func (m *ConnectRequest) GetClientPID() string {
	if m != nil && m.ClientPID != nil {
		return *m.ClientPID
	}
	return ""
}

func (m *ConnectRequest) GetCompress() bool {
	if m != nil && m.Compress != nil {
		return *m.Compress
	}
	return false
}

type ConnectResponse struct {
	CorrelationId    *int32            `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	ServerPID        *string           `protobuf:"bytes,2,opt,name=serverPID" json:"serverPID,omitempty"`
	ErrorCode        *ConnectErrorCode `protobuf:"varint,3,opt,name=errorCode,enum=protobufclient.ConnectErrorCode" json:"errorCode,omitempty"`
	Compress         *bool             `protobuf:"varint,4,opt,name=compress" json:"compress,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}

func (m *ConnectResponse) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *ConnectResponse) GetServerPID() string {
	if m != nil && m.ServerPID != nil {
		return *m.ServerPID
	}
	return ""
}

func (m *ConnectResponse) GetErrorCode() ConnectErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ConnectErrorCode_ALREADY_CONNECTED
}

func (m *ConnectResponse) GetCompress() bool {
	if m != nil && m.Compress != nil {
		return *m.Compress
	}
	return false
}

type RpcRequest struct {
	CorrelationId     *int32  `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	ServiceIdentifier *string `protobuf:"bytes,2,req,name=serviceIdentifier" json:"serviceIdentifier,omitempty"`
	MethodIdentifier  *string `protobuf:"bytes,3,req,name=methodIdentifier" json:"methodIdentifier,omitempty"`
	RequestBytes      []byte  `protobuf:"bytes,4,req,name=requestBytes" json:"requestBytes,omitempty"`
	TimeoutMs         *int32  `protobuf:"varint,5,opt,name=timeoutMs" json:"timeoutMs,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *RpcRequest) Reset()         { *m = RpcRequest{} }
func (m *RpcRequest) String() string { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()    {}

func (m *RpcRequest) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *RpcRequest) GetServiceIdentifier() string {
	if m != nil && m.ServiceIdentifier != nil {
		return *m.ServiceIdentifier
	}
	return ""
}

func (m *RpcRequest) GetMethodIdentifier() string {
	if m != nil && m.MethodIdentifier != nil {
		return *m.MethodIdentifier
	}
	return ""
}

func (m *RpcRequest) GetRequestBytes() []byte {
	if m != nil {
		return m.RequestBytes
	}
	return nil
}

func (m *RpcRequest) GetTimeoutMs() int32 {
	if m != nil && m.TimeoutMs != nil {
		return *m.TimeoutMs
	}
	return 0
}

type RpcResponse struct {
	CorrelationId    *int32 `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	ResponseBytes    []byte `protobuf:"bytes,2,req,name=responseBytes" json:"responseBytes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpcResponse) Reset()         { *m = RpcResponse{} }
func (m *RpcResponse) String() string { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()    {}

func (m *RpcResponse) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *RpcResponse) GetResponseBytes() []byte {
	if m != nil {
		return m.ResponseBytes
	}
	return nil
}

type RpcError struct {
	CorrelationId    *int32  `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	ErrorMessage     *string `protobuf:"bytes,2,req,name=errorMessage" json:"errorMessage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcError) Reset()         { *m = RpcError{} }
func (m *RpcError) String() string { return proto.CompactTextString(m) }
func (*RpcError) ProtoMessage()    {}

func (m *RpcError) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *RpcError) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type RpcCancel struct {
	CorrelationId    *int32 `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpcCancel) Reset()         { *m = RpcCancel{} }
func (m *RpcCancel) String() string { return proto.CompactTextString(m) }
func (*RpcCancel) ProtoMessage()    {}

func (m *RpcCancel) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

type OobResponse struct {
	CorrelationId    *int32 `protobuf:"varint,1,req,name=correlationId" json:"correlationId,omitempty"`
	MessageBytes     []byte `protobuf:"bytes,2,req,name=messageBytes" json:"messageBytes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OobResponse) Reset()         { *m = OobResponse{} }
func (m *OobResponse) String() string { return proto.CompactTextString(m) }
func (*OobResponse) ProtoMessage()    {}

func (m *OobResponse) GetCorrelationId() int32 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *OobResponse) GetMessageBytes() []byte {
	if m != nil {
		return m.MessageBytes
	}
	return nil
}

type OobMessage struct {
	MessageBytes     []byte `protobuf:"bytes,1,req,name=messageBytes" json:"messageBytes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OobMessage) Reset()         { *m = OobMessage{} }
func (m *OobMessage) String() string { return proto.CompactTextString(m) }
func (*OobMessage) ProtoMessage()    {}

func (m *OobMessage) GetMessageBytes() []byte {
	if m != nil {
		return m.MessageBytes
	}
	return nil
}

type WirePayload struct {
	ConnectRequest     *ConnectRequest           `protobuf:"bytes,1,opt,name=connectRequest" json:"connectRequest,omitempty"`
	ConnectResponse    *ConnectResponse          `protobuf:"bytes,2,opt,name=connectResponse" json:"connectResponse,omitempty"`
	RpcRequest         *RpcRequest               `protobuf:"bytes,3,opt,name=rpcRequest" json:"rpcRequest,omitempty"`
	RpcResponse        *RpcResponse              `protobuf:"bytes,4,opt,name=rpcResponse" json:"rpcResponse,omitempty"`
	RpcError           *RpcError                 `protobuf:"bytes,5,opt,name=rpcError" json:"rpcError,omitempty"`
	RpcCancel          *RpcCancel                `protobuf:"bytes,6,opt,name=rpcCancel" json:"rpcCancel,omitempty"`
	OobResponse        *OobResponse              `protobuf:"bytes,7,opt,name=oobResponse" json:"oobResponse,omitempty"`
	OobMessage         *OobMessage               `protobuf:"bytes,8,opt,name=oobMessage" json:"oobMessage,omitempty"`
	TransparentMessage *OobMessage               `protobuf:"bytes,100,opt,name=transparentMessage" json:"transparentMessage,omitempty"`
	XXX_extensions     map[int32]proto.Extension `json:"-"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *WirePayload) Reset()         { *m = WirePayload{} }
func (m *WirePayload) String() string { return proto.CompactTextString(m) }
func (*WirePayload) ProtoMessage()    {}

var extRange_WirePayload = []proto.ExtensionRange{
	{1000, 536870911},
}

func (*WirePayload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_WirePayload
}
func (m *WirePayload) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *WirePayload) GetConnectRequest() *ConnectRequest {
	if m != nil {
		return m.ConnectRequest
	}
	return nil
}

func (m *WirePayload) GetConnectResponse() *ConnectResponse {
	if m != nil {
		return m.ConnectResponse
	}
	return nil
}

func (m *WirePayload) GetRpcRequest() *RpcRequest {
	if m != nil {
		return m.RpcRequest
	}
	return nil
}

func (m *WirePayload) GetRpcResponse() *RpcResponse {
	if m != nil {
		return m.RpcResponse
	}
	return nil
}

func (m *WirePayload) GetRpcError() *RpcError {
	if m != nil {
		return m.RpcError
	}
	return nil
}

func (m *WirePayload) GetRpcCancel() *RpcCancel {
	if m != nil {
		return m.RpcCancel
	}
	return nil
}

func (m *WirePayload) GetOobResponse() *OobResponse {
	if m != nil {
		return m.OobResponse
	}
	return nil
}

func (m *WirePayload) GetOobMessage() *OobMessage {
	if m != nil {
		return m.OobMessage
	}
	return nil
}

func (m *WirePayload) GetTransparentMessage() *OobMessage {
	if m != nil {
		return m.TransparentMessage
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobufclient.ConnectErrorCode", ConnectErrorCode_name, ConnectErrorCode_value)
}
